# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('usertype', models.IntegerField(choices=[(1, '超管'), (2, '普通用户')], default=2)),
                ('regtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
